# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Thesis/Zedboard/Zedboard.cache/wt [current_project]
set_property parent.project_path D:/Thesis/Zedboard/Zedboard.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo d:/Thesis/Zedboard/Zedboard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Thesis/Src/modules/Buffers/Buffer_12_rows.v
  D:/Thesis/Src/modules/Buffers/Buffer_12_rows_ci.v
  D:/Thesis/Src/modules/Buffers/Buffer_4_rows.v
  D:/Thesis/Src/modules/Buffers/Buffer_8_rows.v
  D:/Thesis/Src/modules/MRELBP_CI/CI_top.v
  D:/Thesis/Src/modules/DataModulateModule/3x3/Data_modulate_3x3.v
  D:/Thesis/Src/modules/DataModulateModule/3x3/Data_modulate_3x3_controller.v
  D:/Thesis/Src/modules/DataModulateModule/3x3/Data_modulate_3x3_datapath.v
  D:/Thesis/Src/modules/DataModulateModule/5x5/Data_modulate_5x5.v
  D:/Thesis/Src/modules/DataModulateModule/5x5/Data_modulate_5x5_controller.v
  D:/Thesis/Src/modules/DataModulateModule/5x5/Data_modulate_5x5_datapath.v
  D:/Thesis/Src/modules/DataModulateModule/7x7/Data_modulate_7x7.v
  D:/Thesis/Src/modules/DataModulateModule/7x7/Data_modulate_7x7_controller.v
  D:/Thesis/Src/modules/DataModulateModule/7x7/Data_modulate_7x7_datapath.v
  D:/Thesis/Src/modules/InterpolationModule/Interpolation_R_x.v
  D:/Thesis/Src/modules/InterpolationModule/Interpolation_calc.v
  D:/Thesis/Src/modules/OutputModule/Joint_histogram.v
  D:/Thesis/Src/modules/OutputModule/Joint_histogram_controller.v
  D:/Thesis/Src/modules/OutputModule/Joint_histogram_datapath.v
  D:/Thesis/Src/modules/Buffers/Line_buffer.v
  D:/Thesis/Src/modules/Buffers/LineBuffer/Line_buffer_controller.v
  D:/Thesis/Src/modules/Buffers/LineBuffer/Line_buffer_datapath.v
  D:/Thesis/Src/modules/MRELBP_CI/R2/MRELBP_CI_R2.v
  D:/Thesis/Src/modules/MRELBP_CI/R4/MRELBP_CI_R4.v
  D:/Thesis/Src/modules/MRELBP_CI/R6/MRELBP_CI_R6.v
  D:/Thesis/Src/modules/MedianFilterModule/3x3/Median_filter_3x3.v
  D:/Thesis/Src/modules/MedianFilterModule/3x3/Median_filter_3x3_calc.v
  D:/Thesis/Src/modules/MedianFilterModule/5x5/Median_filter_5x5.v
  D:/Thesis/Src/modules/MedianFilterModule/5x5/Median_filter_5x5_calc.v
  D:/Thesis/Src/modules/MedianFilterModule/7x7/Median_filter_7x7.v
  D:/Thesis/Src/modules/MedianFilterModule/7x7/Median_filter_7x7_calc.v
  D:/Thesis/Src/modules/MedianFilterModule/Median_processing.v
  D:/Thesis/Src/modules/NIRD/NI.v
  D:/Thesis/Src/modules/NIRD/NI_calc.v
  D:/Thesis/Src/modules/MedianFilterModule/Node.v
  D:/Thesis/Src/modules/Buffers/Preparation.v
  D:/Thesis/Src/modules/Buffers/Preparation_6.v
  D:/Thesis/Src/modules/NIRD/R2_NIRD.v
  D:/Thesis/Src/modules/common/R2/R2_controller.v
  D:/Thesis/Src/modules/common/R2/R2_patch_sum.v
  D:/Thesis/Src/modules/common/R2/R2_sum.v
  D:/Thesis/Src/modules/NIRD/R4_NIRD.v
  D:/Thesis/Src/modules/common/R4/R4_controller.v
  D:/Thesis/Src/modules/common/R4/R4_patch_sum.v
  D:/Thesis/Src/modules/common/R4/R4_sum.v
  D:/Thesis/Src/modules/NIRD/R6_NIRD.v
  D:/Thesis/Src/modules/common/R6/R6_controller.v
  D:/Thesis/Src/modules/common/R6/R6_patch_sum.v
  D:/Thesis/Src/modules/common/R6/R6_sum.v
  D:/Thesis/Src/modules/NIRD/RD.v
  D:/Thesis/Src/modules/NIRD/RD_calc.v
  D:/Thesis/Src/modules/MedianFilterModule/5x5/SortAscending5.v
  D:/Thesis/Src/modules/MedianFilterModule/7x7/SortAscending7.v
  D:/Thesis/Src/modules/MedianFilterModule/Sorting_network.v
  D:/Thesis/Src/modules/TopModule/TopModule_controller.v
  D:/Thesis/Src/modules/TopModule/TopModule_datapath.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/11x11/Window_buffer_11x11.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/11x11/Window_buffer_11x11_controller.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/11x11/Window_buffer_11x11_datapath.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/13x13/Window_buffer_13x13.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/13x13/Window_buffer_13x13_controller.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/13x13/Window_buffer_13x13_datapath.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/3x3/Window_buffer_3x3.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/3x3/Window_buffer_3x3_controller.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/3x3/Window_buffer_3x3_datapath.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/5x5/Window_buffer_5x5.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/5x5/Window_buffer_5x5_controller.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/5x5/Window_buffer_5x5_datapath.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/7x7/Window_buffer_7x7.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/7x7/Window_buffer_7x7_controller.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/7x7/Window_buffer_7x7_datapath.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/9x9/Window_buffer_9x9.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/9x9/Window_buffer_9x9_controller.v
  D:/Thesis/Src/modules/Buffers/WindowBuffer/9x9/Window_buffer_9x9_datapath.v
  D:/Thesis/Src/modules/common/dff.v
  D:/Thesis/Src/modules/common/mux_2_1.v
  D:/Thesis/Src/modules/common/plus_1.v
  D:/Thesis/Src/modules/common/register.v
  D:/Thesis/Src/modules/NIRD/riu2_mapping.v
  D:/Thesis/Src/modules/common/shift_registers.v
  D:/Thesis/Src/modules/common/sum.v
  D:/Thesis/Src/modules/common/sum_cumulative.v
  D:/Thesis/Src/modules/TopModule/TopModule.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Thesis/Zedboard/Zedboard.srcs/constrs_1/new/Constraints.xdc
set_property used_in_implementation false [get_files D:/Thesis/Zedboard/Zedboard.srcs/constrs_1/new/Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top TopModule -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopModule.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
