#ifndef _PL_MRELBP_DRIVER_H_
#define _PL_MRELBP_DRIVER_H_

#include <linux/ioctl.h>

#define PL_MRELBP_IOC_MAGIC 'M'

#define CMD_GPIO_START _IO(PL_MRELBP_IOC_MAGIC, 0x01)
#define CMD_DMA_RESET _IO(PL_MRELBP_IOC_MAGIC, 0x02)
#define CMD_DMA_TRANSFER _IO(PL_MRELBP_IOC_MAGIC, 0x03)
#define CMD_GET_RESULT _IO(PL_MRELBP_IOC_MAGIC, 0x04)
#define CMD_CLEAR_BUFFER _IO(PL_MRELBP_IOC_MAGIC, 0x05)

#endif // _PL_MRELBP_DRIVER_H_
