# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Thesis/Zedboard_v/Zedboard_v.runs/synth_1/.Xil/Vivado-18056-DESKTOP-4VU606L/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/Thesis/Src/modules/Buffers/Buffer_12_rows.v
      D:/Thesis/Src/modules/Buffers/Buffer_12_rows_ci.v
      D:/Thesis/Src/modules/Buffers/Buffer_4_rows.v
      D:/Thesis/Src/modules/Buffers/Buffer_8_rows.v
      D:/Thesis/Src/modules/MRELBP_CI/CI_top.v
      D:/Thesis/Src/modules/DataModulateModule/3x3/Data_modulate_3x3.v
      D:/Thesis/Src/modules/DataModulateModule/3x3/Data_modulate_3x3_controller.v
      D:/Thesis/Src/modules/DataModulateModule/3x3/Data_modulate_3x3_datapath.v
      D:/Thesis/Src/modules/DataModulateModule/5x5/Data_modulate_5x5.v
      D:/Thesis/Src/modules/DataModulateModule/5x5/Data_modulate_5x5_controller.v
      D:/Thesis/Src/modules/DataModulateModule/5x5/Data_modulate_5x5_datapath.v
      D:/Thesis/Src/modules/DataModulateModule/7x7/Data_modulate_7x7.v
      D:/Thesis/Src/modules/DataModulateModule/7x7/Data_modulate_7x7_controller.v
      D:/Thesis/Src/modules/DataModulateModule/7x7/Data_modulate_7x7_datapath.v
      D:/Thesis/Src/modules/InterpolationModule/Interpolation_R_x.v
      D:/Thesis/Src/modules/InterpolationModule/Interpolation_calc.v
      D:/Thesis/Src/modules/OutputModule/Joint_histogram.v
      D:/Thesis/Src/modules/OutputModule/Joint_histogram_controller.v
      D:/Thesis/Src/modules/OutputModule/Joint_histogram_datapath.v
      D:/Thesis/Src/modules/Buffers/Line_buffer.v
      D:/Thesis/Src/modules/Buffers/LineBuffer/Line_buffer_controller.v
      D:/Thesis/Src/modules/Buffers/LineBuffer/Line_buffer_datapath.v
      D:/Thesis/Src/modules/MRELBP_CI/R2/MRELBP_CI_R2.v
      D:/Thesis/Src/modules/MRELBP_CI/R4/MRELBP_CI_R4.v
      D:/Thesis/Src/modules/MRELBP_CI/R6/MRELBP_CI_R6.v
      D:/Thesis/Src/modules/MedianFilterModule/3x3/Median_filter_3x3.v
      D:/Thesis/Src/modules/MedianFilterModule/3x3/Median_filter_3x3_calc.v
      D:/Thesis/Src/modules/MedianFilterModule/5x5/Median_filter_5x5.v
      D:/Thesis/Src/modules/MedianFilterModule/5x5/Median_filter_5x5_calc.v
      D:/Thesis/Src/modules/MedianFilterModule/7x7/Median_filter_7x7.v
      D:/Thesis/Src/modules/MedianFilterModule/7x7/Median_filter_7x7_calc.v
      D:/Thesis/Src/modules/MedianFilterModule/Median_processing.v
      D:/Thesis/Src/modules/NIRD/NI.v
      D:/Thesis/Src/modules/NIRD/NI_calc.v
      D:/Thesis/Src/modules/MedianFilterModule/Node.v
      D:/Thesis/Src/modules/Buffers/Preparation.v
      D:/Thesis/Src/modules/Buffers/Preparation_6.v
      D:/Thesis/Src/modules/NIRD/R2_NIRD.v
      D:/Thesis/Src/modules/common/R2/R2_controller.v
      D:/Thesis/Src/modules/common/R2/R2_patch_sum.v
      D:/Thesis/Src/modules/common/R2/R2_sum.v
      D:/Thesis/Src/modules/NIRD/R4_NIRD.v
      D:/Thesis/Src/modules/common/R4/R4_controller.v
      D:/Thesis/Src/modules/common/R4/R4_patch_sum.v
      D:/Thesis/Src/modules/common/R4/R4_sum.v
      D:/Thesis/Src/modules/NIRD/R6_NIRD.v
      D:/Thesis/Src/modules/common/R6/R6_controller.v
      D:/Thesis/Src/modules/common/R6/R6_patch_sum.v
      D:/Thesis/Src/modules/common/R6/R6_sum.v
      D:/Thesis/Src/modules/NIRD/RD.v
      D:/Thesis/Src/modules/NIRD/RD_calc.v
      D:/Thesis/Src/modules/MedianFilterModule/5x5/SortAscending5.v
      D:/Thesis/Src/modules/MedianFilterModule/7x7/SortAscending7.v
      D:/Thesis/Src/modules/MedianFilterModule/Sorting_network.v
      D:/Thesis/Src/modules/TopModule/TopModule_controller.v
      D:/Thesis/Src/modules/TopModule/TopModule_datapath.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/11x11/Window_buffer_11x11.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/11x11/Window_buffer_11x11_controller.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/11x11/Window_buffer_11x11_datapath.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/13x13/Window_buffer_13x13.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/13x13/Window_buffer_13x13_controller.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/13x13/Window_buffer_13x13_datapath.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/3x3/Window_buffer_3x3.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/3x3/Window_buffer_3x3_controller.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/3x3/Window_buffer_3x3_datapath.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/5x5/Window_buffer_5x5.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/5x5/Window_buffer_5x5_controller.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/5x5/Window_buffer_5x5_datapath.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/7x7/Window_buffer_7x7.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/7x7/Window_buffer_7x7_controller.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/7x7/Window_buffer_7x7_datapath.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/9x9/Window_buffer_9x9.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/9x9/Window_buffer_9x9_controller.v
      D:/Thesis/Src/modules/Buffers/WindowBuffer/9x9/Window_buffer_9x9_datapath.v
      D:/Thesis/Src/modules/common/dff.v
      D:/Thesis/Src/modules/common/mux_2_1.v
      D:/Thesis/Src/modules/common/plus_1.v
      D:/Thesis/Src/modules/NIRD/riu2_mapping.v
      D:/Thesis/Src/modules/common/shift_registers.v
      D:/Thesis/Src/modules/common/sum.v
      D:/Thesis/Src/modules/common/sum_cumulative.v
      D:/Thesis/Src/modules/TopModule/TopModule.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Thesis/Zedboard_v/Zedboard_v.runs/synth_1/.Xil/Vivado-18056-DESKTOP-4VU606L/realtime/TopModule_synth.xdc
    rt::sdcChecksum
    set rt::top TopModule
    rt::set_parameter incrementalOnCache "D:/Thesis/Zedboard_v/Zedboard_v.runs/synth_1/.Xil/Vivado-18056-DESKTOP-4VU606L/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Thesis/Zedboard_v/Zedboard_v.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/Thesis/Zedboard_v/Zedboard_v.runs/synth_1/.Xil/Vivado-18056-DESKTOP-4VU606L/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
